routes/web.php
<?php
Route::group(['prefix' => 'auth', 'namespace' => 'Auth'], function () {
    Route::get('login', 'LoginController@showLoginForm')->name('login');
    Route::post('login', 'LoginController@login');
    Route::post('logout', 'LoginController@logout')->name('logout');
    Route::get('register', 'RegisterController@showRegistrationForm')->name('register');
    Route::post('register', 'RegisterController@register');
    Route::get('password/reset', 'ForgotPasswordController@showLinkRequestForm')->name('password.request');
    Route::post('password/email', 'ForgotPasswordController@sendResetLinkEmail')->name('password.email');
    Route::get('password/reset/{token}', 'ResetPasswordController@showResetForm')->name('password.reset');
    Route::post('password/reset', 'ResetPasswordController@reset');
    Route::get('socialite/{provider}', 'AuthController@redirectToProvider');
    Route::get('socialite/{provider}/callback', 'AuthController@handleProviderCallback');
    Route::get('policy-terms-and-conditions', 'AuthController@policytermsandconditions')->name('policy-terms-and-conditions');
});
Route::group(['prefix' => 'admin', 'namespace' => 'Admin', 'middleware' => ['auth', 'roles'], 'block' => ['User']], function () {
    Route::group(['roles' => ['Author', 'Moderator', 'Admin']], function () {
        Route::get('/', 'AdminController@index')->name('admin.index');
    });
    Route::group(['roles' => ['Moderator', 'Admin']], function () {
        Route::resource('products', 'ProductController');
        Route::resource('categories', 'CategoryController');
        Route::resource('brands', 'BrandController');
        Route::resource('mades', 'MadeController');
        Route::resource('reviews', 'ReviewController');
        Route::get('help', 'AdminController@help')->name('admin.help');
        Route::put('help', 'AdminController@helpupdate');
        Route::resource('subscribes', 'SubscribeController');
    });
    Route::group(['roles' => ['Admin']], function () {
        Route::resource('users', 'UserController');
        Route::resource('wishlists', 'WishlistController');
        Route::resource('purchased-commodities', 'PurchasedcommoditiesController');
        Route::get('roles', 'RoleController@index')->name('roles.index');
        Route::get('role/{id}', 'RoleController@show')->name('roles.show');
        Route::get('roles/{id}/edit', 'RoleController@edit')->name('roles.edit');
        Route::put('roles/{id}', 'RoleController@update')->name('roles.update');
        Route::get('settings', 'AdminController@settings')->name('admin.settings');
        Route::put('settings', 'AdminController@settingsupdate');
        Route::get('logs', '\Rap2hpoutre\LaravelLogViewer\LogViewerController@index')->name('admin.logs');
    });
});
Route::namespace('Site')->group(function () {
    Route::get('/', 'SiteController@index')->name('site.index');

    Route::get('men', 'ProductController@men')->name('site.men');
    Route::get('men/{url}', 'ProductController@menview')->name('site.men-view')->where('url', '[\w\d\-\_]+');
    Route::get('men-category/{url}', 'CategoryController@men')->name('site.men-category')->where('url', '[\w\d\-\_]+');
    Route::get('men-brands/{url}', 'BrandController@men')->name('site.men-brands')->where('url', '[\w\d\-\_]+');

    Route::get('women', 'ProductController@women')->name('site.women');
    Route::get('women/{url}', 'ProductController@womenview')->name('site.women-view')->where('url', '[\w\d\-\_]+');
    Route::get('women-category/{url}', 'CategoryController@women')->name('site.women-category')->where('url', '[\w\d\-\_]+');
    Route::get('women-brands/{url}', 'BrandController@women')->name('site.women-brands')->where('url', '[\w\d\-\_]+');

    Route::get('kids', 'ProductController@kids')->name('site.kids');
    Route::get('kids/{url}', 'ProductController@kidsview')->name('site.kids-view')->where('url', '[\w\d\-\_]+');
    Route::get('kids-category/{url}', 'CategoryController@kids')->name('site.kids-category')->where('url', '[\w\d\-\_]+');
    Route::get('kids-brands/{url}', 'BrandController@kids')->name('site.kids-brands')->where('url', '[\w\d\-\_]+');

    Route::get('accessories', 'ProductController@accessories')->name('site.accessories');
    Route::get('accessories/{url}', 'ProductController@accessoriesview')->name('site.accessories-view')->where('url', '[\w\d\-\_]+');
    Route::get('accessories-category/{url}', 'CategoryController@accessories')->name('site.accessories-category')->where('url', '[\w\d\-\_]+');
    Route::get('accessories-brands/{url}', 'BrandController@accessories')->name('site.accessories-brands')->where('url', '[\w\d\-\_]+');

    Route::get('new', 'ProductController@new')->name('site.new');
    Route::get('brands', 'BrandController@brands')->name('site.brands');
    Route::get('trends', 'ProductController@trends')->name('site.trends');
    Route::get('sale', 'ProductController@sale')->name('site.sale');

    Route::get('category/{url}', 'CategoryController@category')->name('site.category')->where('url', '[\w\d\-\_]+');
    Route::get('brands/{url}', 'BrandController@brandsurl')->name('site.brandsurl')->where('url', '[\w\d\-\_]+');
    Route::get('products/{url}', 'ProductController@products')->name('site.products')->where('url', '[\w\d\-\_]+');

    Route::put('review/{id}', 'ProductController@review')->name('site.review')->where('id', '[\w\d\-\_]+');
    Route::put('wishlist/{id}', 'ProductController@wishlist')->name('site.wishlist')->where('id', '[\w\d\-\_]+');

    Route::get('cart', 'CartController@index')->name('cart.index');
    Route::post('cart/{product}', 'CartController@store')->name('cart.store');
    Route::delete('cart/{product}', 'CartController@destroy')->name('cart.destroy');
    Route::delete('emptycart', 'CartController@emptycart')->name('cart.emptycart');

    Route::get('checkout', 'CheckoutController@index')->name('checkout.index')->middleware('auth');
    Route::post('checkout', 'CheckoutController@store')->name('checkout.store');

    Route::get('contact', 'SiteController@contact')->name('site.contact');
    Route::put('contact', 'SiteController@contactpost');

    Route::get('help-faq', 'HelpController@faq')->name('site.help-faq');
    Route::get('help-men', 'HelpController@men')->name('site.help-men');
    Route::get('help-women', 'HelpController@women')->name('site.help-women');
    Route::get('help-kids', 'HelpController@kids')->name('site.help-kids');
    Route::get('help-accessories', 'HelpController@accessories')->name('site.help-accessories');
    Route::get('help-brands', 'HelpController@brands')->name('site.help-brands');

    Route::put('subscribe', 'SubscribeController@subscribe')->name('site.subscribe');

    Route::get('profile', 'ProfileController@index')->name('profile.index');
    Route::get('profile/{id}/edit', 'ProfileController@edit')->name('profile.edit');
    Route::put('profile/{id}/edit', 'ProfileController@updateedit');
    Route::get('profile/{id}/password', 'ProfileController@password')->name('profile.password');
    Route::put('profile/{id}/password', 'ProfileController@updatepassword');
    Route::get('profile/wishlist', 'ProfileController@wishlist')->name('profile.wishlist');
    Route::delete('profile/wishlist{id}', 'ProfileController@wishlistdestroy')->name('profile.wishlistdestroy');
    Route::get('profile/{id}/purchased-commodities', 'ProfileController@purchasedcommodities')->name('profile.purchased-commodities');
});

app/Category.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Category extends Model
{
    protected $fillable = ['name', 'url', 'men', 'women', 'kids', 'accessories', 'status'];

    public function products()
    {
        return $this->hasMany('App\Product');
    }
}

app/Http/Controllers/Admin/CategoryController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Category;
use App\Http\Requests\Category as Request;


class CategoryController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $main = Category::all();
        return view('admin.categories.index', compact('main'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.categories.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        Category::create($request->all());
        return redirect()->route('categories.index')->with('success', __('admin.created-success'));
    }

    /**
     * Display the specified resource.
     *
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $main = Category::find($id);
        return view('admin.categories.show', compact('main'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $main = Category::find($id);
        return view('admin.categories.edit', compact('main'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        Category::find($id)->update($request->all());
        return redirect()->route('categories.index')->with('success', __('admin.updated-success'));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        Category::find($id)->delete();
        return redirect()->route('categories.index')->with('success', __('admin.information-deleted'));
    }
}

app/Http/Controllers/Site/CategoryController.php
<?php

namespace App\Http\Controllers\Site;

use App\Brand;
use App\Category;
use App\Http\Controllers\Controller;
use App\Product;

class CategoryController extends Controller
{
    public function men($url)
    {
        $men = Category::where('url', $url)->where('status', 1)->where('men', 1)->first();
        if (isset($men)) {
            $id = $men->id;
            $title = $men->name;
            $main = Product::where('type_id', 1)->where('status', 1)->where('category_id', $id)->paginate(10);
            $brands = Brand::where('status', 1)->get();
            $category = Category::where('status', 1)->where('men', 1)->get();
            return view('site.products.mencategory', compact('main', 'title', 'category', 'brands'));
        } else {
            abort(404);
        }
    }

    public function women($url)
    {
        $women = Category::where('url', $url)->where('status', 1)->where('women', 1)->first();
        if (isset($women)) {
            $id = $women->id;
            $title = $women->name;
            $main = Product::where('type_id', 2)->where('status', 1)->where('category_id', $id)->paginate(10);
            $brands = Brand::where('status', 1)->get();
            $category = Category::where('status', 1)->where('women', 1)->get();
            return view('site.products.womencategory', compact('main', 'title', 'category', 'brands'));
        } else {
            abort(404);
        }
    }

    public function kids($url)
    {
        $kids = Category::where('url', $url)->where('status', 1)->where('kids', 1)->first();
        if (isset($kids)) {
            $id = $kids->id;
            $title = $kids->name;
            $main = Product::where('type_id', 3)->where('status', 1)->where('category_id', $id)->paginate(10);
            $brands = Brand::where('status', 1)->get();
            $category = Category::where('status', 1)->where('kids', 1)->get();
            return view('site.products.kidscategory', compact('main', 'title', 'category', 'brands'));
        } else {
            abort(404);
        }
    }

    public function accessories($url)
    {
        $accessories = Category::where('url', $url)->where('status', 1)->where('accessories', 1)->first();
        if (isset($accessories)) {
            $id = $accessories->id;
            $title = $accessories->name;
            $main = Product::where('type_id', 4)->where('status', 1)->where('category_id', $id)->paginate(10);
            $brands = Brand::where('status', 1)->get();
            $category = Category::where('status', 1)->where('accessories', 1)->get();
            return view('site.products.accessoriescategory', compact('main', 'title', 'category', 'brands'));
        } else {
            abort(404);
        }
    }

    public function category($url)
    {
        $category = Category::where('url', $url)->where('status', 1)->first();
        if (isset($category)) {
            $id = $category->id;
            $title = $category->name;
            $main = Product::where('status', 1)->where('category_id', $id)->paginate(10);
            $brands = Brand::where('status', 1)->get();
            $category = Category::where('status', 1)->get();
            return view('site.products.category', compact('main', 'title', 'category', 'brands'));
        } else {
            abort(404);
        }
    }
}

resources/views/admin/categories/create.blade.php
@extends('admin.layouts.main')

@section('title',__('admin.create-categories'))

@section('content')
    @include('admin.includes.title')
    @include('admin.includes.error')
    <form action="{{ route('categories.store') }}" method="POST">
        @csrf
        <div class="form-group">
            <label>{{ __('admin.categories-name') }}</label>
            <input type="text" class="form-control" name="name" value="{{ old('name') }}"
                   placeholder="{{ __('admin.categories-enter-name') }}" required>
        </div>

        <div class="form-group">
            <label>{{ __('admin.categories-url') }}</label>
            <input type="text" class="form-control" name="url" value="{{ old('url') }}"
                   placeholder="{{ __('admin.categories-enter-url') }}" required>
        </div>

        <div class="form-group">
            <label>{{ __('admin.categories-men') }}</label>
            <select class="form-control" name="men" required>
                <option value="1">{{ __('admin.enabled') }}</option>
                <option value="0">{{ __('admin.disabled') }}</option>
            </select>
        </div>

        <div class="form-group">
            <label>{{ __('admin.categories-women') }}</label>
            <select class="form-control" name="women" required>
                <option value="1">{{ __('admin.enabled') }}</option>
                <option value="0">{{ __('admin.disabled') }}</option>
            </select>
        </div>

        <div class="form-group">
            <label>{{ __('admin.categories-kids') }}</label>
            <select class="form-control" name="kids" required>
                <option value="1">{{ __('admin.enabled') }}</option>
                <option value="0">{{ __('admin.disabled') }}</option>
            </select>
        </div>

        <div class="form-group">
            <label>{{ __('admin.categories-accessories') }}</label>
            <select class="form-control" name="accessories" required>
                <option value="1">{{ __('admin.enabled') }}</option>
                <option value="0">{{ __('admin.disabled') }}</option>
            </select>
        </div>

        <div class="form-group">
            <label>{{ __('admin.status') }}</label>
            <select class="form-control" name="status" required>
                <option value="1">{{ __('admin.enabled') }}</option>
                <option value="0">{{ __('admin.disabled') }}</option>
            </select>
        </div>

        <button class="btn btn-lg btn-original btn-block" type="submit">{{ __('admin.create') }}</button>
    </form>
@endsection

resources/views/admin/categories/edit.blade.php
@extends('admin.layouts.main')

@section('title',__('admin.edit-categories'))

@section('content')
    @include('admin.includes.title')
    @include('admin.includes.error')
    <form action="{{ route('categories.update',$main->id) }}" method="POST">
        @csrf
        @method('PUT')
        <div class="form-group">
            <label>{{ __('admin.categories-name') }}</label>
            <input type="text" class="form-control" name="name" value="{{ $main->name }}"
                   placeholder="{{ __('admin.categories-name') }}" required>
        </div>

        <div class="form-group">
            <label>{{ __('admin.categories-url') }}</label>
            <input type="text" class="form-control" name="url" value="{{ $main->url }}"
                   placeholder="{{ __('admin.categories-url') }}" required>
        </div>

        <div class="form-group">
            <label>{{ __('admin.categories-men') }}</label>
            <select class="form-control" name="men" required>
                @if($main->men)
                    <option value="1">{{ __('admin.enabled') }}</option>
                    <option value="0">{{ __('admin.disabled') }}</option>
                @else
                    <option value="0">{{ __('admin.disabled') }}</option>
                    <option value="1">{{ __('admin.enabled') }}</option>
                @endif
            </select>
        </div>

        <div class="form-group">
            <label>{{ __('admin.categories-women') }}</label>
            <select class="form-control" name="women" required>
                @if($main->women)
                    <option value="1">{{ __('admin.enabled') }}</option>
                    <option value="0">{{ __('admin.disabled') }}</option>
                @else
                    <option value="0">{{ __('admin.disabled') }}</option>
                    <option value="1">{{ __('admin.enabled') }}</option>
                @endif
            </select>
        </div>

        <div class="form-group">
            <label>{{ __('admin.categories-kids') }}</label>
            <select class="form-control" name="kids" required>
                @if($main->kids)
                    <option value="1">{{ __('admin.enabled') }}</option>
                    <option value="0">{{ __('admin.disabled') }}</option>
                @else
                    <option value="0">{{ __('admin.disabled') }}</option>
                    <option value="1">{{ __('admin.enabled') }}</option>
                @endif
            </select>
        </div>

        <div class="form-group">
            <label>{{ __('admin.categories-accessories') }}</label>
            <select class="form-control" name="accessories" required>
                @if($main->accessories)
                    <option value="1">{{ __('admin.enabled') }}</option>
                    <option value="0">{{ __('admin.disabled') }}</option>
                @else
                    <option value="0">{{ __('admin.disabled') }}</option>
                    <option value="1">{{ __('admin.enabled') }}</option>
                @endif
            </select>
        </div>

        <div class="form-group">
            <label>{{ __('admin.status') }}</label>
            <select class="form-control" name="status" required>
                @if($main->status)
                    <option value="1">{{ __('admin.enabled') }}</option>
                    <option value="0">{{ __('admin.disabled') }}</option>
                @else
                    <option value="0">{{ __('admin.disabled') }}</option>
                    <option value="1">{{ __('admin.enabled') }}</option>
                @endif
            </select>
        </div>

        <button class="btn btn-lg btn-original btn-block" type="submit">{{ __('admin.edit') }}</button>
    </form>
@endsection

resources/views/admin/categories/index.blade.php
@extends('admin.layouts.main')

@section('title',__('admin.categories-title'))

@section('content')
    <div class="row justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
        <div class="col-lg-9">
            <div class="d-flex">
                <h1 class="h2">@yield('title')</h1>
                <div class="btn-toolbar mb-2 mb-md-0">
                </div>
            </div>
        </div>
        <div class="col-lg-3">
            <div class="pull-right">
                <a class="btn btn-original" href="{{ route('categories.create') }}">{{ __('admin.create-categories') }}</a>
            </div>
        </div>
    </div>
    @include('admin.includes.success')
    <div class="table-responsive">
        <table id="datatable" class="table table-striped table-bordered" style="width:100%">
            <thead>
            <tr>
                <th scope="col">{{ __('admin.categories-id') }}</th>
                <th scope="col">{{ __('admin.categories-name') }}</th>
                <th scope="col">{{ __('admin.categories-url') }}</th>
                <th scope="col">{{ __('admin.categories-men') }}</th>
                <th scope="col">{{ __('admin.categories-women') }}</th>
                <th scope="col">{{ __('admin.categories-kids') }}</th>
                <th scope="col">{{ __('admin.categories-accessories') }}</th>
                <th scope="col">{{ __('admin.status') }}</th>
                <th scope="col"></th>
            </tr>
            </thead>
            <tbody>
            @foreach($main as $item)
                <tr>
                    <th scope="row">{{ $item->id }}</th>
                    <td scope="row">{{ $item->name }}</td>
                    <td scope="row">{{ $item->url }}</td>
                    <td scope="row">
                        @if($item->men)
                            {{ __('admin.enabled') }}
                        @else
                            {{ __('admin.disabled') }}
                        @endif
                    </td>
                    <td scope="row">
                        @if($item->women)
                            {{ __('admin.enabled') }}
                        @else
                            {{ __('admin.disabled') }}
                        @endif
                    </td>
                    <td scope="row">
                        @if($item->kids)
                            {{ __('admin.enabled') }}
                        @else
                            {{ __('admin.disabled') }}
                        @endif
                    </td>
                    <td scope="row">
                        @if($item->accessories)
                            {{ __('admin.enabled') }}
                        @else
                            {{ __('admin.disabled') }}
                        @endif
                    </td>
                    <td scope="row">
                        @if($item->status)
                            {{ __('admin.enabled') }}
                        @else
                            {{ __('admin.disabled') }}
                        @endif
                    </td>
                    <td scope="row">
                        <a href="{{ route('categories.show',$item->id) }}"><i class="far fa-eye"></i></a>
                        <a href="{{ route('categories.edit',$item->id) }}"><i class="fas fa-edit"></i></a>
                        <form action="{{ route('categories.destroy',$item->id) }}" method="POST">
                            @csrf
                            @method('DELETE')
                            <button type="submit"><i class="fas fa-trash-alt"></i></button>
                        </form>

                    </td>
                </tr>
            @endforeach
            </tbody>
        </table>
    </div>
@endsection

resources/views/admin/categories/show.blade.php
@extends('admin.layouts.main')

@section('title',__('admin.show-categories'))

@section('content')
    @include('admin.includes.title')
    <ul class="nav mb-md-3">
        <li>
            <a href="{{ route('categories.index') }}" class="btn btn-dark">{{ __('admin.back') }}</a>
            <a href="{{ route('categories.edit', $main->id) }}" class="btn btn-primary">{{ __('admin.update') }}</a>
            <form action="{{ route('categories.destroy', $main->id) }}" method="POST">
                @csrf
                @method('DELETE')
                <button type="submit" class="btn btn-danger">{{ __('admin.delete') }}</button>
            </form>
        </li>
    </ul>
    <table class="table">
        <tr>
            <th>{{ __('admin.categories-id') }}</th>
            <td>{{ $main->id }}</td>
        </tr>

        <tr>
            <th>{{ __('admin.categories-name') }}</th>
            <td>{{ $main->name }}</td>
        </tr>
        <tr>
            <th>{{ __('admin.categories-url') }}</th>
            <td>{{ $main->url }}</td>
        </tr>
        <tr>
            <th>{{ __('admin.categories-men') }}</th>
            <td>
                @if($main->men)
                    {{ __('admin.enabled') }}
                @else
                    {{ __('admin.disabled') }}
                @endif
            </td>
        </tr>
        <tr>
            <th>{{ __('admin.categories-women') }}</th>
            <td>
                @if($main->women)
                    {{ __('admin.enabled') }}
                @else
                    {{ __('admin.disabled') }}
                @endif
            </td>
        </tr>
        <tr>
            <th>{{ __('admin.categories-kids') }}</th>
            <td>
                @if($main->kids)
                    {{ __('admin.enabled') }}
                @else
                    {{ __('admin.disabled') }}
                @endif
            </td>
        </tr>
        <tr>
            <th>{{ __('admin.categories-accessories') }}</th>
            <td>
                @if($main->accessories)
                    {{ __('admin.enabled') }}
                @else
                    {{ __('admin.disabled') }}
                @endif
            </td>
        </tr>
        <tr>
            <th>{{ __('admin.status') }}</th>
            <td>
                @if($main->status)
                    {{ __('admin.enabled') }}
                @else
                    {{ __('admin.disabled') }}
                @endif
            </td>
        </tr>
        <tr>
            <th>{{ __('admin.created') }}</th>
            <td>{{ $main->created_at }}</td>
        </tr>
        <tr>
            <th>{{ __('admin.update') }}</th>
            <td>{{ $main->updated_at }}</td>
        </tr>
    </table>
@endsection