routes/web.php
<?php
Route::group(['prefix' => 'auth', 'namespace' => 'Auth'], function () {
    Route::get('login', 'LoginController@showLoginForm')->name('login');
    Route::post('login', 'LoginController@login');
    Route::post('logout', 'LoginController@logout')->name('logout');
    Route::get('register', 'RegisterController@showRegistrationForm')->name('register');
    Route::post('register', 'RegisterController@register');
    Route::get('password/reset', 'ForgotPasswordController@showLinkRequestForm')->name('password.request');
    Route::post('password/email', 'ForgotPasswordController@sendResetLinkEmail')->name('password.email');
    Route::get('password/reset/{token}', 'ResetPasswordController@showResetForm')->name('password.reset');
    Route::post('password/reset', 'ResetPasswordController@reset');
    Route::get('socialite/{provider}', 'AuthController@redirectToProvider');
    Route::get('socialite/{provider}/callback', 'AuthController@handleProviderCallback');
    Route::get('policy-terms-and-conditions', 'AuthController@policytermsandconditions')->name('policy-terms-and-conditions');
});
Route::group(['prefix' => 'admin', 'namespace' => 'Admin', 'middleware' => ['auth', 'roles'], 'block' => ['User']], function () {
    Route::group(['roles' => ['Author', 'Moderator', 'Admin']], function () {
        Route::get('/', 'AdminController@index')->name('admin.index');
    });
    Route::group(['roles' => ['Moderator', 'Admin']], function () {
        Route::resource('products', 'ProductController');
        Route::resource('categories', 'CategoryController');
        Route::resource('brands', 'BrandController');
        Route::resource('mades', 'MadeController');
        Route::resource('reviews', 'ReviewController');
        Route::get('help', 'AdminController@help')->name('admin.help');
        Route::put('help', 'AdminController@helpupdate');
        Route::resource('subscribes', 'SubscribeController');
    });
    Route::group(['roles' => ['Admin']], function () {
        Route::resource('users', 'UserController');
        Route::resource('wishlists', 'WishlistController');
        Route::resource('purchased-commodities', 'PurchasedcommoditiesController');
        Route::get('roles', 'RoleController@index')->name('roles.index');
        Route::get('role/{id}', 'RoleController@show')->name('roles.show');
        Route::get('roles/{id}/edit', 'RoleController@edit')->name('roles.edit');
        Route::put('roles/{id}', 'RoleController@update')->name('roles.update');
        Route::get('settings', 'AdminController@settings')->name('admin.settings');
        Route::put('settings', 'AdminController@settingsupdate');
        Route::get('logs', '\Rap2hpoutre\LaravelLogViewer\LogViewerController@index')->name('admin.logs');
    });
});
Route::namespace('Site')->group(function () {
    Route::get('/', 'SiteController@index')->name('site.index');

    Route::get('men', 'ProductController@men')->name('site.men');
    Route::get('men/{url}', 'ProductController@menview')->name('site.men-view')->where('url', '[\w\d\-\_]+');
    Route::get('men-category/{url}', 'CategoryController@men')->name('site.men-category')->where('url', '[\w\d\-\_]+');
    Route::get('men-brands/{url}', 'BrandController@men')->name('site.men-brands')->where('url', '[\w\d\-\_]+');

    Route::get('women', 'ProductController@women')->name('site.women');
    Route::get('women/{url}', 'ProductController@womenview')->name('site.women-view')->where('url', '[\w\d\-\_]+');
    Route::get('women-category/{url}', 'CategoryController@women')->name('site.women-category')->where('url', '[\w\d\-\_]+');
    Route::get('women-brands/{url}', 'BrandController@women')->name('site.women-brands')->where('url', '[\w\d\-\_]+');

    Route::get('kids', 'ProductController@kids')->name('site.kids');
    Route::get('kids/{url}', 'ProductController@kidsview')->name('site.kids-view')->where('url', '[\w\d\-\_]+');
    Route::get('kids-category/{url}', 'CategoryController@kids')->name('site.kids-category')->where('url', '[\w\d\-\_]+');
    Route::get('kids-brands/{url}', 'BrandController@kids')->name('site.kids-brands')->where('url', '[\w\d\-\_]+');

    Route::get('accessories', 'ProductController@accessories')->name('site.accessories');
    Route::get('accessories/{url}', 'ProductController@accessoriesview')->name('site.accessories-view')->where('url', '[\w\d\-\_]+');
    Route::get('accessories-category/{url}', 'CategoryController@accessories')->name('site.accessories-category')->where('url', '[\w\d\-\_]+');
    Route::get('accessories-brands/{url}', 'BrandController@accessories')->name('site.accessories-brands')->where('url', '[\w\d\-\_]+');

    Route::get('new', 'ProductController@new')->name('site.new');
    Route::get('brands', 'BrandController@brands')->name('site.brands');
    Route::get('trends', 'ProductController@trends')->name('site.trends');
    Route::get('sale', 'ProductController@sale')->name('site.sale');

    Route::get('category/{url}', 'CategoryController@category')->name('site.category')->where('url', '[\w\d\-\_]+');
    Route::get('brands/{url}', 'BrandController@brandsurl')->name('site.brandsurl')->where('url', '[\w\d\-\_]+');
    Route::get('products/{url}', 'ProductController@products')->name('site.products')->where('url', '[\w\d\-\_]+');

    Route::put('review/{id}', 'ProductController@review')->name('site.review')->where('id', '[\w\d\-\_]+');
    Route::put('wishlist/{id}', 'ProductController@wishlist')->name('site.wishlist')->where('id', '[\w\d\-\_]+');

    Route::get('cart', 'CartController@index')->name('cart.index');
    Route::post('cart/{product}', 'CartController@store')->name('cart.store');
    Route::delete('cart/{product}', 'CartController@destroy')->name('cart.destroy');
    Route::delete('emptycart', 'CartController@emptycart')->name('cart.emptycart');

    Route::get('checkout', 'CheckoutController@index')->name('checkout.index')->middleware('auth');
    Route::post('checkout', 'CheckoutController@store')->name('checkout.store');

    Route::get('contact', 'SiteController@contact')->name('site.contact');
    Route::put('contact', 'SiteController@contactpost');

    Route::get('help-faq', 'HelpController@faq')->name('site.help-faq');
    Route::get('help-men', 'HelpController@men')->name('site.help-men');
    Route::get('help-women', 'HelpController@women')->name('site.help-women');
    Route::get('help-kids', 'HelpController@kids')->name('site.help-kids');
    Route::get('help-accessories', 'HelpController@accessories')->name('site.help-accessories');
    Route::get('help-brands', 'HelpController@brands')->name('site.help-brands');

    Route::put('subscribe', 'SubscribeController@subscribe')->name('site.subscribe');

    Route::get('profile', 'ProfileController@index')->name('profile.index');
    Route::get('profile/{id}/edit', 'ProfileController@edit')->name('profile.edit');
    Route::put('profile/{id}/edit', 'ProfileController@updateedit');
    Route::get('profile/{id}/password', 'ProfileController@password')->name('profile.password');
    Route::put('profile/{id}/password', 'ProfileController@updatepassword');
    Route::get('profile/wishlist', 'ProfileController@wishlist')->name('profile.wishlist');
    Route::delete('profile/wishlist{id}', 'ProfileController@wishlistdestroy')->name('profile.wishlistdestroy');
    Route::get('profile/{id}/purchased-commodities', 'ProfileController@purchasedcommodities')->name('profile.purchased-commodities');
});

resources/views/admin/includes/error.blade.php
@if ($errors->any())
    <div class="alert alert-danger alert-dismissible fade show">
        <ul>
            @foreach ($errors->all() as $error)
                <li>{{ $error }}</li>
            @endforeach
        </ul>
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
    </div>
@endif

resources/views/admin/includes/nav.blade.php
<nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
    <a class="navbar-brand" href="{{ route('admin.index') }}">{{ __('admin.admin-panel') }}</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse"
            aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarCollapse">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item {{ url()->current() == route('admin.index') ? 'active' : '' }}">
                <a class="nav-link" href="{{ route('admin.index') }}"><i class="fas fa-home"></i> {{ __('admin.nav-home') }}
                </a>
            </li>
            @if(in_array(Auth::user()->role->name, ['Moderator','Admin']))
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button"
                       data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        <i class="fas fa-shopping-cart"></i> {{ __('admin.nav-online-shop') }}</a>
                    <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                        <a class="dropdown-item {{ Request::is('*products*') ? 'active' : '' }}"
                           href="{{ route('products.index') }}"><i
                                    class="fas fa-tshirt"></i> {{ __('admin.nav-products') }}</a>
                        <a class="dropdown-item {{ Request::is('*categories*') ? 'active' : '' }}"
                           href="{{ route('categories.index') }}"><i
                                    class="fab fa-amilia"></i> {{ __('admin.nav-categories') }}</a>
                        <a class="dropdown-item {{ Request::is('*brands*') ? 'active' : '' }}"
                           href="{{ route('brands.index') }}"><i
                                    class="fas fa-anchor"></i> {{ __('admin.nav-brands') }}</a>
                        <a class="dropdown-item {{ Request::is('*mades*') ? 'active' : '' }}"
                           href="{{ route('mades.index') }}"><i
                                    class="fas fa-globe"></i> {{ __('admin.nav-mades') }}</a>
                        <a class="dropdown-item {{ Request::is('*reviews*') ? 'active' : '' }}"
                           href="{{ route('reviews.index') }}"><i
                                    class="fas fa-comments"></i> {{ __('admin.nav-reviews') }}</a>
                    </div>
                </li>
                <li class="nav-item {{ Request::is('*help*') ? 'active' : '' }}">
                    <a class="nav-link" href="{{ route('admin.help') }}"><i class="fas fa-question-circle"></i> {{ __('admin.nav-help') }}
                    </a>
                </li>
                <li class="nav-item {{ Request::is('*subscribes*') ? 'active' : '' }}">
                    <a class="nav-link" href="{{ route('subscribes.index') }}"><i class="fas fa-bell"></i> {{ __('admin.nav-subscribes') }}
                    </a>
                </li>
            @endif
            @if(in_array(Auth::user()->role->name, ['Admin']))
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button"
                       data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        <i class="fas fa-users-cog"></i> {{ __('admin.nav-user-manager') }}</a>
                    <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                        <a class="dropdown-item {{ Request::is('*users*') ? 'active' : '' }}"
                           href="{{ route('users.index') }}"><i
                                    class="fas fa-users"></i> {{ __('admin.nav-users') }}</a>
                        <a class="dropdown-item {{ Request::is('*roles*') ? 'active' : '' }}"
                           href="{{ route('roles.index') }}"><i
                                    class="fas fa-user-shield"></i> {{ __('admin.nav-roles') }}</a>
                        <a class="dropdown-item {{ Request::is('*wishlists*') ? 'active' : '' }}"
                           href="{{ route('wishlists.index') }}"><i
                                    class="fas fa-list-ul"></i> {{ __('admin.nav-wishlists') }}</a>
                        <a class="dropdown-item {{ Request::is('*purchased-commodities*') ? 'active' : '' }}"
                           href="{{ route('purchased-commodities.index') }}"><i
                                    class="fas fa-list-ol"></i> {{ __('admin.nav-purchased-commodities') }}</a>
                    </div>
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button"
                       data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        <i class="fas fa-cogs"></i> {{ __('admin.nav-settings') }}</a>
                    <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                        <a class="dropdown-item {{ Request::is('*settings*') ? 'active' : '' }}"
                           href="{{ route('admin.settings') }}"><i
                                    class="fas fa-wrench"></i> {{ __('admin.nav-settings') }}</a>
                        <a class="dropdown-item {{ Request::is('*logs*') ? 'active' : '' }}"
                           href="{{ route('admin.logs') }}"><fa-cogsi
                                    class="fas fa-calendar"></fa-cogsi> {{ __('admin.nav-logs') }}</a>
                    </div>
                </li>
            @endif
        </ul>
        <ul class="navbar-nav">
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button"
                   data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    <i class="fas fa-user"></i> {{ Auth::user()->name }}
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                    <a class="dropdown-item {{ url()->current() == route('profile.index') ? 'active' : '' }}"
                       href="{{ route('profile.index') }}"><i
                                class="far fa-user-circle"></i> {{ __('admin.nav-profile') }}</a>
                    <a class="dropdown-item" href="{{ route('logout') }}"
                       onclick="event.preventDefault();document.getElementById('logout-form').submit();"><i
                                class="fas fa-sign-out-alt"></i> {{ __('admin.nav-logout') }}</a>
                    <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                        @csrf
                    </form>
                </div>
            </li>
        </ul>
    </div>
</nav>

resources/views/admin/includes/success.blade.php
@if (session('success'))
    <div class="alert alert-success alert-dismissible fade show">
        {{ session('success') }}
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
    </div>
@endif

resources/views/admin/includes/title.blade.php
<div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
    <h1 class="h2">@yield('title')</h1>
    <div class="btn-toolbar mb-2 mb-md-0">
    </div>
</div>